### ISSUE TITLE
Uncaught TypeError: Cannot read property 'replace' of undefined

### ISSUE THREAD

**Issue by bahasdu** [joelgardner/git-line#10]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.17.0 x64
**Electron**: 1.3.15
**OS**: Microsoft Windows 10 Enterprise
**Thrown From**: [git-line](https://github.com/joelgardner/git-line) package 0.6.0

### Stack Trace

Uncaught TypeError: Cannot read property 'replace' of undefined

```
At /C:/Users/Bakytzhan_Manaspayev/.atom/packages/git-line/lib/output-parser.js:24

TypeError: Cannot read property 'replace' of undefined
    at Object.parseAuthorEmail (/packages/git-line/lib/output-parser.js:21:41)
    at Object.parseOutput (/packages/git-line/lib/output-parser.js:10:19)
    at /packages/git-line/lib/git-line.js:71:73
    at ChildProcess.exithandler (child_process.js:209:7)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
```

### Commands

```
     -5:00.2.0 fuzzy-finder:toggle-file-finder (input.hidden-input)
     -4:59 editor:consolidate-selections (input.hidden-input)
     -4:59 core:cancel (input.hidden-input)
     -4:57 git-time-machine:toggle (input.hidden-input)
     -4:02.4.0 split-diff:copy-to-left (span.syntax--text.syntax--html.syntax--basic)
     -3:51 git-line:toggle (div.line-number.cursor-line.split-diff-added)
  3x -2:44.4.0 core:move-right (input.hidden-input)
     -2:42.8.0 editor:move-to-end-of-screen-line (input.hidden-input)
     -0:34.7.0 git-line:toggle (div.line-number.cursor-line.git-line-modified)
```

### Non-Core Packages

```
atom-beautify 0.29.24 
atom-less 0.1.10 
atom-ternjs 0.16.1 
autocomplete-java 1.2.5 
copy-filename 1.0.1 
default-language 0.3.0 
file-icons 1.7.25 
file-types 0.5.5 
git-line 0.6.0 
git-plus 7.0.7 
git-time-machine 1.5.9 
go-find-references 1.2.3 
goto-last-edit 0.3.3 
language-groovy 0.7.0 
last-cursor-position 0.9.2 
recent-files-fuzzy-finder 0.3.1 
tabs-to-spaces 1.0.3 
```

**Comment by joelgardner** [comment]
Thanks @bahasdu -- I am taking a look at this today, hope to have a fix up soon!
