### ISSUE TITLE
Uncaught TypeError: Cannot read property 'indexOf' of undefined

### ISSUE THREAD

**Issue by PhilippRott** [joelgardner/git-line#11]
[Enter steps to reproduce:]

1. installed package git-line
2. toggle git-line

**Atom**: 1.18.0 x64
**Electron**: 1.3.15
**OS**: Ubuntu 16.04.2
**Thrown From**: [git-line](https://github.com/joelgardner/git-line) package 0.6.0

### Stack Trace

Uncaught TypeError: Cannot read property 'indexOf' of undefined

```
At /home/rott/.atom/packages/git-line/lib/git-line.js:79

TypeError: Cannot read property 'indexOf' of undefined
    at Object.message (/packages/git-line/lib/git-line.js:79:36)
    at /packages/git-line/lib/git-line.js:71:58
    at ChildProcess.exithandler (child_process.js:209:7)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Socket.<anonymous> (internal/child_process.js:334:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:493:12)
```

### Commands

```
     -0:48.5.0 tree-view:show (atom-workspace.workspace.scrollbars-visible-always)
     -0:25 timecop:view (div.tool-panel.tree-view)
     -0:05.6.0 git-line:toggle (input.hidden-input)
```

### Non-Core Packages

```
atom-beautify 0.30.4 
autocomplete-clang 0.11.3 
build 0.68.0 
busy 0.7.0 
file-icons 2.1.9 
git-line 0.6.0 
git-plus 7.9.3 
git-time-machine 1.5.9 
intentions 1.1.5 
language-ini 1.19.0 
linter 2.2.0 
linter-gcc 0.7.1 
linter-ui-default 1.6.3 
minimap 4.29.3 
platformio-ide 2.0.0-beta.7 
platformio-ide-debugger 1.2.3 
platformio-ide-terminal 2.5.4 
symbols-tree-view 0.14.0 
tool-bar 1.1.0 
tree-view-git-status 1.4.0 
```

**Comment by nezed** [comment]
**Atom**: 1.22.0 x64
**Electron**: 1.6.15
**OS**: Mac OS X 10.13.1
**Thrown From**: [git-line](https://github.com/joelgardner/git-line) package 0.6.0


### Stack Trace

Uncaught TypeError: Cannot read property 'indexOf' of undefined

```
At /Users/nezed/.atom/packages/git-line/lib/git-line.js:79

TypeError: Cannot read property 'indexOf' of undefined
    at Object.message (/packages/git-line/lib/git-line.js:79:36)
    at /packages/git-line/lib/git-line.js:71:58
    at ChildProcess.exithandler (child_process.js:214:7)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:885:16)
    at Socket.<anonymous> (internal/child_process.js:334:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:501:12)
```

### Commands

```
     -1:38.5.0 core:save (input.hidden-input)
     -1:38.2.0 core:close (input.hidden-input)
     -1:35.5.0 project-find:show (div.results-view.focusable-panel)
     -1:34 core:backspace (input.hidden-input)
     -1:33.7.0 core:confirm (input.hidden-input)
     -1:25.1.0 project-find:show (div.results-view.focusable-panel)
     -1:24.8.0 core:paste (input.hidden-input)
     -1:24.4.0 core:confirm (input.hidden-input)
     -1:16.4.0 nuclide-file-tree:remove-project-folder-selection (div.header.list-item)
     -1:15.2.0 application:add-project-folder (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-dark-syntax.theme-one-dark-ui.find-visible)
     -1:06.9.0 core:select-all (input.hidden-input)
     -1:06.7.0 core:backspace (input.hidden-input)
     -1:06.4.0 core:confirm (input.hidden-input)
     -0:58 command-palette:toggle (input.hidden-input)
     -0:56.2.0 core:confirm (input.hidden-input)
     -0:56.2.0 git-line:toggle (input.hidden-input)
```

### Non-Core Packages

```
atom-beautify 0.30.6 
editorconfig 2.2.2 
git-control 0.9.0 
git-line 0.6.0 
git-time-machine 1.5.9 
language-babel 2.78.0 
language-javascript-jsx 0.3.7 
language-postcss 1.3.1 
linter 2.2.0 
merge-conflicts 1.4.5 
nuclide 0.267.0 
```

**Comment by alexandrelheinen** [comment]
Any known reason for it? I have the same issue for projects that are not on Github.

**Comment by niels-numbers** [comment]
I have the same issue. I use BitBucket as repository. Will it work on GitLab?
