### ISSUE TITLE
Uncaught TypeError: Cannot read property 'buffer' of undefined

### ISSUE THREAD

**Issue by rafaelhcs** [joelgardner/git-line#15]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.44.0 x64
**Electron**: 4.2.7
**OS**: Unknown Windows version
**Thrown From**: [git-line](https://github.com/joelgardner/git-line) package 0.6.0

### Stack Trace

Uncaught TypeError: Cannot read property 'buffer' of undefined

```
At C:\Users\FDL\.atom\packages\git-line\lib\git-line.js:51

TypeError: Cannot read property 'buffer' of undefined
    at /packages/git-line/lib/git-line.js:51:31
    at Object.toggle (/packages/git-line/lib/git-line.js:73:10)
    at HTMLElement.gitLineToggle (/packages/git-line/lib/git-line.js:25:37)
    at CommandRegistry.handleCommandEvent (~/AppData/Local/atom/app-1.44.0/resources/app/static/<embedded>:11:349290)
    at KeymapManager.dispatchCommandEvent (~/AppData/Local/atom/app-1.44.0/resources/app/static/<embedded>:11:1253613)
    at KeymapManager.handleKeyboardEvent (~/AppData/Local/atom/app-1.44.0/resources/app/static/<embedded>:11:1249747)
    at WindowEventHandler.handleDocumentKeyEvent (~/AppData/Local/atom/app-1.44.0/resources/app/static/<embedded>:11:284496)
```

### Commands

```
     -5:10.9.0 core:copy (input.hidden-input)
     -5:06.7.0 core:paste (input.hidden-input)
  2x -4:39.5.0 core:save (input.hidden-input)
     -4:19.4.0 core:delete (input.hidden-input)
  2x -3:06.8.0 core:backspace (input.hidden-input)
  2x -3:03.1.0 core:delete (input.hidden-input)
     -3:02.1.0 core:move-down (input.hidden-input)
  2x -3:01.9.0 core:move-left (input.hidden-input)
     -3:01.3.0 core:move-down (input.hidden-input)
     -3:01.2.0 core:move-left (input.hidden-input)
     -3:00.3.0 core:backspace (input.hidden-input)
  2x -2:59.2.0 core:save (input.hidden-input)
  2x -0:13.1.0 git-line:toggle (div.package-detail)
```

### Non-Core Packages

```
git-line 0.6.0 
remote-ftp 2.2.4 
```

**Comment by joelgardner** [comment]
Thanks for submitting this issue. I have moved on from Atom to VSCode and other responsibilities are enough to keep me from sufficiently maintaining this repo. 

Of course, I will happily accept PRs! Please feel free to submit a patch for this issue.
